config/routes.rb
Smartrooms::Application.routes.draw do

  resources :rooms do
    get '/all/reservations',  to: 'rooms#reservation'
    post '/search' => 'reservations#search'
    resources :reservations do
    end
  end

  resources :users, except: [:index]

  resources :sessions, only: [:new, :create, :destroy]

  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  root :to => 'smart_reservations#index', :constraints => lambda{|req| !req.session[:user_id].blank?}, as: :authenticated_root
  root :to => 'static_pages#home'

  get '/smart_reservations/facets',  to: 'smart_reservations#facets'
  get '/smart_reservations/values/:facet', to: 'smart_reservations#values'
  get '/smart_reservations/search',  to: 'smart_reservations#search', as: :search

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase unless :guest? }
  before_create :create_remember_token
  validates :name, presence: true
  validates :email, presence: true, unless: :guest?
  validates :name, uniqueness: true, allow_blank: true

  has_secure_password

  has_many :room_user, :dependent => :destroy
  has_many :associations, :through => :room_user, :source => :room,  :dependent => :destroy
  has_many :rooms, :foreign_key => 'owner_id'
  has_many :reservations, :foreign_key => 'owner_id'

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def self.new_guest
    random = rand(36**6).to_s(36)
    new guest: true, password: "guest", password_confirmation: "guest", name: "Guest_#{random}"
  end

  def move_to(user)
    rooms.update_all(owner_id: user.id)
    reservations.update_all(owner_id: user.id)
    room_user.update_all(user_id: user.id)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  skip_authorization_check :only => [:new, :create]

  # GET /users/1
  # GET /users/1.json
  def show
    @myrooms = Room.where(owner: current_user).paginate(:page => params[:page], :per_page => 3)
    @belongsrooms = Room.includes(:users).where(users: { id: current_user.id}).paginate(:page => params[:page], :per_page => 3)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = params[:user] ? User.new(user_params) : User.new_guest

    respond_to do |format|
      if @user.save
        current_user.move_to(@user) if current_user && current_user.guest?
        sign_in @user
        format.html { redirect_to @user, :flash => { success: 'User was successfully created. Welcome!' } }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, :flash => { success: 'User was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, :flash => { success: 'User was successfully destroyed.' }  }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <%= render 'shared/error_messages', obj: f.object  %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <hr>
    <%= f.submit 'Confirm', class: "btn btn-large btn-primary"%>

<% end %>

app/views/users/_my_rooms.html.erb
<table class="table table-striped table-hover rooms">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% rooms.each do |room| %>
      <tr data-link="<%= room_path(room) %>" class='table_row'>
        <td><%= room.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate rooms %>

app/views/users/_rooms.html.erb
<table class="table table-striped table-hover rooms">
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
    </tr>
  </thead>

  <tbody>
    <% rooms.each do |room| %>
      <tr data-link="<%= room_path(room) %>" class='table_row'>
        <td><%= room.name %></td>
        <td><%= room.owner.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate rooms %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
    <p>Rumble Judge? <%= link_to "Guest user!", users_path, method: :post %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <h1><%= @user.name %></h1>
      <h3><%= @user.email %></h3>
    </section>
    <section>
      <h4>
        <% if not current_user.guest? %>
          <% if can? :manage, @user %>
            <%= link_to 'Edit', edit_user_path(@user) %> |
          <%end%>
        <%end%>  
        <% if current_user.guest? %>
          <%= link_to "Become a member", signup_path %> |
        <% end %>
        <%= link_to 'Back', :back %>
      </h4>
    </section>
  </aside>
  <% if can? :manage, @user %>
  <aside class="span8">
    <h1>My Rooms</h1>
    <%= render 'my_rooms', rooms: @myrooms %>
  </aside>
  <aside class="span8 offset4">
    <h1>Rooms i belongs</h1>
    <%= render 'rooms', rooms: @belongsrooms %>
  </aside>
  <%end%>
</div>