config/routes.rb
Smartrooms::Application.routes.draw do

  resources :rooms do
    get '/all/reservations',  to: 'rooms#reservation'
    post '/search' => 'reservations#search'
    resources :reservations do
    end
  end

  resources :users, except: [:index]

  resources :sessions, only: [:new, :create, :destroy]

  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  root :to => 'smart_reservations#index', :constraints => lambda{|req| !req.session[:user_id].blank?}, as: :authenticated_root
  root :to => 'static_pages#home'

  get '/smart_reservations/facets',  to: 'smart_reservations#facets'
  get '/smart_reservations/values/:facet', to: 'smart_reservations#values'
  get '/smart_reservations/search',  to: 'smart_reservations#search', as: :search

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  belongs_to :owner, :foreign_key => "owner_id", :class_name => "User"
  belongs_to :room

  validates :initial_date, presence: true
  validates :end_date, presence: true
  validates :room_id, presence: true
  validate :interception
  validate :initial_date_cannot_be_in_the_past
  validate :end_date_greather_than_initial_date

  default_scope { order("initial_date ASC") }

  def interception
    reservations =
      Reservation.where(
        '((initial_date BETWEEN :initial_date AND :end_date OR end_date BETWEEN :initial_date AND :end_date)
        OR (initial_date <= :initial_date AND end_date >= :end_date))
        AND room_id = :room_id',
        end_date: end_date, initial_date: initial_date, room_id: room.id)

    if (reservations - [self]).count > 0
       errors.add(:base, 'This reservation has intercession date / time with another reservation')
    end
  end

  def initial_date_cannot_be_in_the_past
    errors.add(:initial_date, "can't be in the past") if
      !initial_date.blank? and initial_date < Date.today - 10.minutes
  end

  def end_date_greather_than_initial_date
    errors.add(:end_date, "Must be greather than initial date") if
      end_date <= initial_date
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  load_and_authorize_resource :room
  load_and_authorize_resource :through => :room

  def search
    index
    render :index
  end

  # GET /reservations
  # GET /reservations.json
  def index
    @search = @reservations.search(params[:q])
    @reservations = @search.result.paginate(:page => params[:page])
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation.owner_id = current_user.id
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = @room.reservations.build(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to [@room, @reservation], :flash => { success: 'Reservation was successfully created.' } }
        format.json { render action: 'show', status: :created, location: @reservation }
      else
        format.html { render action: 'new' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to [@reservation.room, @reservation] , :flash => { success: 'Reservation was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to @room,  :flash => { success: 'Reservation was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:initial_date, :end_date, :owner_id, :reason)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for [@room, @reservation] do |f| %>

  <%= render 'shared/error_messages', obj: f.object  %>

  <%= f.hidden_field :owner_id %>

  <%= f.label 'What I want to do?' %>
  <%= f.text_field :reason %>

  <%= f.label :initial_date %>
  <div class="input-append date datetimepicker">
    <%= f.text_field :initial_date, data: {format: "yyyy-MM-dd hh:mm"} %>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>

  <%= f.label :end_date %>
  <div class="input-append date datetimepicker">
    <%= f.text_field :end_date, data: {format: "yyyy-MM-dd hh:mm"} %>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>

  <hr>

  <%= f.submit 'Confirm', class: "btn btn-large btn-primary"%>

<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Show', [@room, @reservation] %> |
<%= link_to 'Back', :back %>

app/views/reservations/index.html.erb
<%- model_class = Reservation -%>
<h1>Listing reservations</h1>

<%= search_form_for @search, url: room_search_path(@room),
                        class: 'search',
                        html: { method: :post } do |f| %>
  <div class="input-append pull-right">
    <%= f.text_field :initial_date_eq, :class => 'span2', :placeholder => 'Search' %>
    <%= button_tag(type: 'submit', :class => 'btn') do %>
      <i class="icon-search"></i>
    <% end %>
  </div>
<% end %>

<table class="table table-striped table-hover rooms">
  <thead>
    <tr>
      <th><%= sort_link @search, :initial_date, model_class.human_attribute_name(:initial_date) %></th>
      <th><%= sort_link @search, :end_date, model_class.human_attribute_name(:end_date) %></th>
      <th></th>
      <th><%= sort_link @search, :reason, model_class.human_attribute_name(:reason) %></th>
      <th><%= sort_link @search, :owner, model_class.human_attribute_name(:owner) %></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr data-link="<%= room_reservation_path(reservation.room, reservation) %>" class='table_row'>
        <td><%= reservation.initial_date.to_formatted_s(:short)   %></td>
        <td><%= reservation.end_date.to_formatted_s(:short)   %></td>
        <td><%= distance_of_time_in_words(reservation.initial_date, reservation.end_date) %></td>
        <td><%= reservation.reason %></td>
        <td><%= reservation.owner.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_room_reservation_path(@room), class: 'btn btn-primary' %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Back', :back %>

app/views/reservations/show.html.erb
<%- model_class = Reservation -%>
<div class="row">
  <aside class="span3">
    <section>
      <h1><%= @reservation.room.name %></h1>
    </section>
    <section>
      <h4>
        <%= link_to 'Edit', edit_room_reservation_path(@room, @reservation) %> |
        <%= link_to 'Destroy', [@room, @reservation], method: :delete, data: { confirm: 'Are you sure?' } %> |
        <%= link_to 'Back', @room %>
      </h4>
    </section>
  </aside>
  <aside class="span9">
    <h1>Reservation Infos</h1>
     <section class='well'>
      <%= content_tag :h3, model_class.human_attribute_name(:owner) %>
      <%= content_tag :p, @reservation.owner.name  %>
      <%= content_tag :h3, model_class.human_attribute_name(:initial_date) %>
      <%= content_tag :p, @reservation.initial_date.to_formatted_s(:long) %>
      <%= content_tag :h3, model_class.human_attribute_name(:end_date) %>
      <%= content_tag :p, @reservation.end_date.to_formatted_s(:long) %>
      <%= content_tag :h3, model_class.human_attribute_name(:reason) %>
      <%= content_tag :p, @reservation.reason %>
      <%= content_tag :h3, 'Time' %>
      <%= content_tag :p, distance_of_time_in_words(@reservation.initial_date, @reservation.end_date) %>
     </section>
  </aside>
</div>