config/routes.rb
Smartrooms::Application.routes.draw do

  resources :rooms do
    get '/all/reservations',  to: 'rooms#reservation'
    post '/search' => 'reservations#search'
    resources :reservations do
    end
  end

  resources :users, except: [:index]

  resources :sessions, only: [:new, :create, :destroy]

  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  root :to => 'smart_reservations#index', :constraints => lambda{|req| !req.session[:user_id].blank?}, as: :authenticated_root
  root :to => 'static_pages#home'

  get '/smart_reservations/facets',  to: 'smart_reservations#facets'
  get '/smart_reservations/values/:facet', to: 'smart_reservations#values'
  get '/smart_reservations/search',  to: 'smart_reservations#search', as: :search

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :room_user, :dependent => :destroy
  has_many :users, :through => :room_user, :after_remove => :remove_reservations
	belongs_to :owner, :foreign_key => "owner_id", :class_name => "User"
  has_many :reservations, :dependent => :destroy
  validates :name, presence: true

  private

    def remove_reservations(user)
      self.reservations.where('owner_id = ?', user.id).delete_all
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include ActionView::Helpers::DateHelper
  load_and_authorize_resource

  before_action :list_associates, only: [:new, :edit]

  # GET /rooms
  # GET /rooms.json
  def index
    @search = @rooms.search(params[:q])
    @rooms = @search.result.paginate(:page => params[:page])
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @search = @room.reservations.search(params[:q])
    @reservations = @search.result.where("initial_date > ?", Date.today).paginate(:page => params[:page], :per_page => 4)
  end

  # GET /rooms/new
  def new
    @room.owner_id = current_user.id
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, :flash => { success: 'Room was successfully created.' } }
        format.json { render action: 'show', status: :created, location: @room }
      else
        format.html { render action: 'new' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update

    respond_to do |format|
      if @room.update(room_params_update)
        format.html { redirect_to @room, :flash => { success: 'Room was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url :flash => { success: 'Room was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  def reservation
    reservations = Room.find(params.require(:room_id)).reservations.map do |r|
      {
        startDate: r.initial_date.strftime('%Y/%m/%d %H:%M:%S'),
        endDate: r.end_date.strftime('%Y/%m/%d %H:%M:%S'),
        title: "#{r.owner.name} for #{r.reason.empty? ? 'a not defined metting' : r.reason} ends #{r.end_date.strftime('%m/%d %H:%M')} will take #{distance_of_time_in_words(r.initial_date, r.end_date)}",
        description: "#{r.initial_date.strftime('%Y/%m/%d %H:%M:%S')} to #{r.end_date.strftime('%Y/%m/%d %H:%M:%S')}",
        priority: 3,
        frecuency: 1
      }
    end
    render :json => reservations
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:owner_id, :name, {:user_ids => [] })

    end

    def room_params_update
      params.require(:room).permit(:name, {:user_ids => [] })

    end

    def list_associates
      @associates = User.all - [current_user]
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>

  <%= render 'shared/error_messages', obj: f.object  %>

  <%= f.hidden_field :owner_id %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :who_can_uses_this_room? %>
  
  <%= f.select :user_ids, 
    @associates.map { |u| [u.name, u.id] },
    { include_blank: true },
    { class: 'chosen-select', multiple: true }
  %>
  <hr>
  <%= f.submit 'Confirm', class: "btn btn-large btn-primary"%>

<% end %>

app/views/rooms/_room.html.erb
<%- owner_name = room.owner == current_user ? "You" : room.owner.name -%>
<li>
  <span><%= link_to "#{room.name} belongs to #{owner_name}",
  new_room_reservation_path(room), data: { params: 'lol'}, :onclick => '' %></span>
</li>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>


<%= link_to 'Show', @room %> |
<%= link_to 'Back', :back %>

app/views/rooms/index.html.erb
<%- model_class = Room -%>
<h1>Listing rooms</h1>

<%= search_form_for @search, :class => 'search' do |f| %>
  <div class="input-append pull-right">
    <%= f.text_field :name_cont, :class => 'span2', :placeholder => 'Search' %>
    <%= button_tag(type: 'submit', :class => 'btn') do %>
      <i class="icon-search"></i>
    <% end %>
  </div>
<% end %>

<%= will_paginate %>

<table class="table table-striped table-hover rooms">
  <thead>
    <tr>
      <th><%= sort_link @search, :name, model_class.human_attribute_name(:name) %></th>
      <th><%= sort_link @search, :owner, model_class.human_attribute_name(:owner) %></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr data-link="<%= room_path(room) %>" class='table_row'>
        <td><%= room.name %></td>
        <td><%= room.owner == current_user ? "I'm the owner" : room.owner.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

<%= link_to 'New Room', new_room_path, class: 'btn btn-primary'%>

app/views/rooms/new.html.erb
<h1>New room</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>


<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<%- model_class = Reservation -%>
<div class="row">
  <aside class="span3">
    <section>
      <h1><%= @room.name %></h1>
      <h3><%= @room.owner.name %></h3>
    </section>
    <section>
      <p>
        <% @room.users.each_with_index do |u, index| %>
          <%= link_to u == current_user ? "me" : u.name, u %><%= ',' unless index == @room.users.size - 1%>
        <% end %>
      </p>
    </section>
    <section>
      <h4>
        <% if can? :manage, @room %>
          <%= link_to 'Edit', edit_room_path(@room) %> |
          <%= link_to 'All Reservations', room_reservations_path(@room) %> |
          <%= link_to 'Destroy', @room, method: :delete, data: { confirm: 'Are you sure?' } %> |
        <% end %>
        <%= link_to 'Back', rooms_path %>
      </h4>
    </section>
  </aside>
  <section class='span9'>
    <h1>Reservations</h1>
  </section>
  <section class="span5">
    <%= content_tag :div, "", id: "calendar", data: {room: @room.id} %>
  </section>
  <section class="span4">

    <table class="table table-striped table-hover rooms">
      <thead>
        <tr>
          <th><%= sort_link @search, :owner, model_class.human_attribute_name(:owner) %></th>
          <th><%= sort_link @search, :reason, model_class.human_attribute_name(:reason) %></th>
          <th><%= sort_link @search, :initial_date, model_class.human_attribute_name(:initial_date) %></th>
          <th><%= sort_link @search, :end_date, model_class.human_attribute_name(:end_date) %></th>
        </tr>
      </thead>

      <tbody>
        <% @reservations.each do |reservation| %>
          <tr data-link="<%= room_reservation_path(@room, reservation) %>" class='table_row'>
            <td><%= reservation.owner == current_user ? "I'm the owner" : reservation.owner.name %></td>
            <td><%= reservation.reason %></td> 
            <td><%= reservation.initial_date.to_formatted_s(:short)   %></td>
            <td><%= reservation.end_date.to_formatted_s(:short)   %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @reservations %>
    <%= link_to 'New Reservation', new_room_reservation_path(@room), class: 'btn btn-primary'%>

  </section>
</div>