config/routes.rb
Smartrooms::Application.routes.draw do

  resources :rooms do
    get '/all/reservations',  to: 'rooms#reservation'
    post '/search' => 'reservations#search'
    resources :reservations do
    end
  end

  resources :users, except: [:index]

  resources :sessions, only: [:new, :create, :destroy]

  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  root :to => 'smart_reservations#index', :constraints => lambda{|req| !req.session[:user_id].blank?}, as: :authenticated_root
  root :to => 'static_pages#home'

  get '/smart_reservations/facets',  to: 'smart_reservations#facets'
  get '/smart_reservations/values/:facet', to: 'smart_reservations#values'
  get '/smart_reservations/search',  to: 'smart_reservations#search', as: :search

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "SmartRooms", root_path %>
    by
    <%= link_to "gporpino", 'https://github.com/gporpino', target: '_blank' %>
    and
    <%= link_to "hamorim", 'https://github.com/hamorim', target: '_blank' %>
    build for
    <%= link_to image_tag('rumble.png', :alt => 'Rumble 2013 Participant', :title => 'Rumble 2013 Participant'), 'http://railsrumble.com/', target: '_blank' %>.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "SmartRooms", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Rooms", rooms_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <% if current_user.guest? %>
                  <li><%= link_to "Become a member", signup_path %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", signup_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_vote.html.erb
<script type="text/javascript">
  var rumbleBannerBackgroundColor, rumbleBannerTextColor, rumbleBannerLinkColor, rumbleBannerPlacement;
  rumbleBannerBackgroundColor = "#161616";
  rumbleBannerTextColor = "#b0b0b0";
  rumbleBannerLinkColor = "#ffffff";
  rumbleBannerPlacement = "bottom";
</script>
<script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartRooms</title>
    <link rel="avicon" href="/favicon.ico" />
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'shared/analytics' %>
    <%= render 'layouts/vote' %>
  </body>

</html>